
# SEO settings
title: "bay"
title2: "chay" # default: ""
description: "Just another minimalist Jekyll theme for technical writing."
keywords: "Jekyll, blog, Artificial Intelligence, AI, Deep Learning, Machine Learning, Computer Vision, Neural Networks, Generative, GAN, Recurrent, Recurrent Neural Networks, RNN, Natural Language Processing, NLP, Music, Blues, Rock, RHCP, Hendrix, Sabbath, Nirvana"
url: http://botcs.github.io/blog/ # site url
baseurl: /blog # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/botcs/blog
disqus_shortname: "@csaba_botos"
twitter_username: "Csaba Botos"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Csaba Botos"
  thumb    : images/author.jpg
  email    : botos.official@gmail.com
  url      : http://botcs.github.io
  github   : http://github.com/botcs
  twitter  : http://twitter.com/csaba_botos
  linkedin : https://www.linkedin.com/in/botos-csaba/

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@csaba_botos"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
